export const DAEJANGDONG_TOPIC = {
  id: "daejangdong",
  title: "대장동 사건 타임라인",
  description: "개발사업의 출발부터 수사와 재판, 항소 포기와 수사 방식 논쟁까지. 서로 다른 사건의 경과와 당사자들의 주장을 출처와 함께 읽습니다.",
  reviewedAt: "2026-10-04",
} as const;

type ResearchSource = { title: string; publisher: string; publishedAt: string; url: string; access: string };
export const researchSources = {
  early: { title: "[일지] '대장동 의혹' 화천대유 설립부터 이재명 기소까지", publisher: "연합뉴스 · 파이낸셜뉴스 전재", publishedAt: "2023-03-22", url: "https://www.fnnews.com/news/202303221112242017", access: "전재 기사 본문 확인" },
  indictmentChronology: { title: "[일지]이재명, '대장동·위례' 재판行…의혹 등장부터 기소까지", publisher: "뉴시스", publishedAt: "2023-03-22", url: "https://www.newsis.com/view/NISX20230322_0002236116", access: "검색 색인 확인" },
  renewedInvestigation: { title: "'2010년대 초' 대장동 관계자들 부르는 수사팀…이재명 혐의 찾나", publisher: "뉴시스", publishedAt: "2022-07-30", url: "https://www.newsis.com/view/NISX20220729_0001961880", access: "기사 본문 확인" },
  leeResponse: { title: "1조 원 대장동 개발 의혹…이재명 '모범적 공익사업'", publisher: "SBS", publishedAt: "2021-09-15", url: "https://news.sbs.co.kr/news/endPage.do?news_id=N1006465949", access: "검색 색인 확인" },
  debate: { title: "이재명 '대장동 의혹' 총정리…공익 환수? 배당 특혜?", publisher: "SBS · 주영진의 뉴스브리핑", publishedAt: "2021-09-15", url: "https://news.sbs.co.kr/news/endPage.do?news_id=N1006466699", access: "방송사 기사 검색 색인 확인 · 전체 방송 미전사" },
  firstTrial: { title: "이재명, 대장동 첫 공판에 출석…정진상과 법정서 '포옹'", publisher: "SBS", publishedAt: "2023-10-06", url: "https://news.sbs.co.kr/news/endPage.do?news_id=N1007373513", access: "검색 색인 확인" },
  trial2024: { title: "이재명, 재판 또 불출석…'특혜 논란' vs '선거 중요'", publisher: "SBS", publishedAt: "2024-03-19", url: "https://news.sbs.co.kr/news/endPage.do?news_id=N1007578594", access: "방송사 기사 검색 색인 확인" },
  trialArguments: { title: "법정 싸움 시작된 검찰 對 이재명…'성남시 손해' vs '이익 낸 사업'", publisher: "SBS", publishedAt: "2023-11-04", url: "https://news.sbs.co.kr/news/endPage.do?news_id=N1007409684", access: "검색 색인 확인 · 11월 20일 수정 기사" },
  kimFirst: { title: "[일지] 대장동 수사부터 김용 '불법자금' 1심 선고까지", publisher: "연합뉴스", publishedAt: "2023-11-30", url: "https://www.yna.co.kr/amp/view/AKR20231130133500004", access: "검색 색인 확인" },
  kimAppeal: { title: "'불법 정치자금·뇌물' 김용, 항소심도 징역 5년…법정구속", publisher: "뉴시스", publishedAt: "2025-02-06", url: "https://www.newsis.com/view/NISX20250206_0003055433", access: "검색 색인 확인" },
  leeDelay: { title: "이재명 대통령 '대장동 재판'도 연기…공범 재판은 그대로", publisher: "머니투데이", publishedAt: "2025-06-10", url: "https://www.mt.co.kr/society/2025/06/10/2025061014535880216", access: "검색 색인 확인" },
  kimBail: { title: "대법, 李대통령 측근 김용 보석 석방…불구속 상고심 재판(종합)", publisher: "연합뉴스", publishedAt: "2025-08-19", url: "https://www.yna.co.kr/view/AKR20250819134451004", access: "검색 색인 확인" },
  kimResponse: { title: "김용 전 민주연구원 부원장, 보석 석방…'억울하지만 진실 밝혀질 것'", publisher: "MBC", publishedAt: "2025-08-20", url: "https://imnews.imbc.com/news/2025/politics/article/6747423_36712.html", access: "검색 색인 확인" },
  mainVerdict: { title: "[종합] '대장동 비리' 김만배·유동규 징역 8년 법정구속", publisher: "뉴스핌", publishedAt: "2025-10-31", url: "https://www.newspim.com/news/view/20251031001257", access: "기사 본문 확인 · 판결문 전문 미확보" },
  appealDecision: { title: "[일지] 대장동 '항소 포기'부터 노만석 사퇴까지", publisher: "뉴스핌", publishedAt: "2025-11-14", url: "https://www.newspim.com/news/view/20251114001073", access: "기사 본문 및 검색 색인 확인" },
  minister: { title: "정성호 '대장동 항소포기 문제없어…檢에 신중히 판단하라 얘기'", publisher: "서울신문", publishedAt: "2025-11-10", url: "https://www.seoul.co.kr/news/society/2025/11/10/20251110500091", access: "검색 색인 확인" },
  mainAppeal: { title: "대장동 일당, 항소심 첫 재판에서 '배임 무죄' 주장", publisher: "YTN", publishedAt: "2026-01-23", url: "https://www.ytn.co.kr/_ln/0103_202601232304592654", access: "방송사 기사 검색 색인 확인" },
  gwakSeparate: { title: "檢, '대장동 50억' 곽상도 부자 1심 항소…'사실오인·법리오해'(종합)", publisher: "연합뉴스", publishedAt: "2026-02-12", url: "https://www.yna.co.kr/view/AKR20260212190351004", access: "검색 색인 확인" },
  gwakAppeal: { title: "'대장동 50억' 곽상도 항소심 재개…'검찰, 남욱 진술 회유'", publisher: "연합뉴스", publishedAt: "2026-04-14", url: "https://www.yna.co.kr/view/AKR20260414119800004", access: "검색 색인 확인" },
  hearing: { title: "남욱 '檢, 구치감에서 진술 압박'…'남욱, 계속 말 바꿔' 녹취 공개", publisher: "TV조선", publishedAt: "2026-04-17", url: "https://news.tvchosun.com/site/data/html_dir/2026/04/17/2026041790017.html", access: "방송사 기사 검색 색인 확인 · 청문회 전체 미전사" },
  hearingRulingParty: { title: "범여권 국조특위 위원들 '대장동 수사, 李 겨냥 기획수사…특검으로 책임'", publisher: "서울신문", publishedAt: "2026-04-17", url: "https://www.seoul.co.kr/news/politics/2026/04/17/20260417500130", access: "검색 색인 확인" },
  hearingOpposition: { title: "국힘 '억지 답정너 특검에 공소취소권 주나'…남욱 등 위증 고발(종합)", publisher: "연합뉴스", publishedAt: "2026-04-30", url: "https://www.yna.co.kr/view/AKR20260430069551001", access: "검색 색인 확인" },
  mainBail: { title: "'대장동 의혹' 정민용·정영학 보석 허가…5명 모두 석방", publisher: "SBS", publishedAt: "2026-05-31", url: "https://news.sbs.co.kr/news/endPage.do?news_id=N1008588041", access: "검색 색인 확인 · 4월 30일/5월 7일 절차를 후속 보도" },
  kimRecords: { title: "법무부 검찰미래위 '김용 사건 기록' 열람 요청에 대법원 '불허'", publisher: "한겨레", publishedAt: "2026-07-09", url: "https://www.hani.co.kr/arti/society/society_general/1267440.html", access: "검색 색인 확인" },
  latestTestimony: { title: "'대장동 민간업자' 정민용…'검찰, 짜여진 틀 이미 있었다 생각'", publisher: "뉴시스", publishedAt: "2026-09-18", url: "https://www.newsis.com/view/NISX20260918_0003795510", access: "기사 본문 확인 · 공판조서 전문 미확보" },
} as const satisfies Record<string, ResearchSource>;

export type ResearchSourceId = keyof typeof researchSources;
export const timelineCategories = ["사업 배경", "의혹·반박", "수사·기소", "재판·절차", "정치적 대응"] as const;
export type TimelineCategory = typeof timelineCategories[number];
export const caseTracks = ["개발사업·민간업자", "이재명·정진상", "김용 정치자금", "50억 클럽", "수사·정치 논쟁"] as const;
export type CaseTrack = typeof caseTracks[number];
export const timelinePeriods = [
  { id: "background", title: "개발사업의 출발", range: "2011~2015", description: "개발 방식의 전환과 사업자 선정, 이후 논쟁의 출발점을 살펴봅니다." },
  { id: "investigation", title: "의혹 확산과 초기 수사", range: "2021", description: "공익 환수와 특혜 논쟁이 수사와 기소로 이어집니다." },
  { id: "expansion", title: "수사 확대와 재판 시작", range: "2022~2023", description: "민간업자 사건에서 정치자금과 이재명·정진상 사건으로 수사가 확대됩니다." },
  { id: "judgments", title: "공판과 선고, 재판 연기와 항소 포기", range: "2024~2025", description: "어느 피고인의 어떤 재판 결과인지 나눠 읽습니다." },
  { id: "recent", title: "항소심과 수사 방식 논쟁", range: "2026", description: "청문회 주장과 반박, 석방과 법정 증언을 구분합니다." },
] as const;
type TimelineEntry = { id: string; date: string; dateLabel: string; period: typeof timelinePeriods[number]["id"]; category: TimelineCategory; track: CaseTrack; title: string; body: string; limit: string; sources: readonly ResearchSourceId[] };

export const timelineEntries: readonly TimelineEntry[] = [
  { id: "public-development", date: "2011-03", dateLabel: "2011.03 (월 단위 확인)", period: "background", category: "사업 배경", track: "개발사업·민간업자", title: "성남시, 공영개발 추진 결정", body: "민영개발을 추진하던 시기를 거쳐 성남시가 대장동 공영개발 추진을 결정했다. 이후 사업은 민관합동 방식으로 진행됐다.", limit: "후속 수사 보도로 확인한 개발 방식의 전환이다. 이 자료에서는 정확한 결정일과 행정 문서 원문을 확보하지 못했다.", sources: ["renewedInvestigation", "leeResponse"] },
  { id: "company", date: "2015-02-06", dateLabel: "2015.02.06", period: "background", category: "사업 배경", track: "개발사업·민간업자", title: "화천대유 설립", body: "대장동 개발사업에 참여한 화천대유자산관리가 설립됐다.", limit: "회사 설립일은 범죄 성립에 관한 판단이 아니다.", sources: ["early"] },
  { id: "selection", date: "2015-03-27", dateLabel: "2015.02.13 공모 · 03.27 선정", period: "background", category: "사업 배경", track: "개발사업·민간업자", title: "민간사업자 공모와 하나은행 컨소시엄 선정", body: "성남도시개발공사가 공모를 거쳐 화천대유가 참여한 컨소시엄을 선정했다.", limit: "선정 절차와 특혜 여부에 대한 이후의 수사·재판 판단을 구분한다.", sources: ["early"] },
  { id: "lee-public-interest", date: "2021-09-14", dateLabel: "2021.09.14 (15일 보도)", period: "investigation", category: "의혹·반박", track: "이재명·정진상", title: "이재명, 공익 환수 사업이라는 입장", body: "이재명은 대장동 개발 의혹에 대해 성남시민에게 5,503억 원의 이익을 환수한 모범적 공익사업이라는 취지로 설명했다.", limit: "당시 당사자의 설명이다. 환수액의 산정 방식이나 배임 여부가 확정됐다는 뜻은 아니다.", sources: ["leeResponse"] },
  { id: "broadcast-debate", date: "2021-09-15", dateLabel: "2021.09.15 방송", period: "investigation", category: "의혹·반박", track: "수사·정치 논쟁", title: "공익 환수인가, 민간에 대한 배당 특혜인가", body: "SBS ‘주영진의 뉴스브리핑’에서 송평수는 공영개발 전환과 공공 환수, 민간의 사업 위험을 강조했다. 김경율은 공공이 위험을 부담하고 민간이 큰 이익을 얻는 구조를 비판했다.", limit: "서로 다른 평가를 요약했다. 방송 토론 자체가 회계 검증이나 재판의 결론은 아니다.", sources: ["debate"] },
  { id: "recordings", date: "2021-09-27", dateLabel: "2021.09.27", period: "investigation", category: "수사·기소", track: "개발사업·민간업자", title: "정영학, 녹취파일을 검찰에 제출", body: "정영학이 대장동 관계자들의 대화를 담은 녹취파일을 수사기관에 냈다.", limit: "제출 사실을 기록한다. 녹음 원본 전체나 개별 발언의 진위·증거능력을 독립 검증한 것은 아니다.", sources: ["early"] },
  { id: "searches", date: "2021-09-29", dateLabel: "2021.09.29", period: "investigation", category: "수사·기소", track: "개발사업·민간업자", title: "전담수사팀 구성과 압수수색", body: "검찰이 전담수사팀을 꾸리고 화천대유와 성남도시개발공사 등을 압수수색했다.", limit: "강제수사 착수는 유죄 판결이 아니다.", sources: ["early"] },
  { id: "yoo-indictment", date: "2021-10-21", dateLabel: "2021.10.01 체포 · 10.21 기소", period: "investigation", category: "수사·기소", track: "개발사업·민간업자", title: "유동규 체포와 뇌물 혐의 구속기소", body: "검찰은 유동규 전 공사 본부장을 체포한 뒤 뇌물 혐의 등으로 구속기소했다.", limit: "이 단계의 혐의와 이후 추가된 배임 등 공소사실은 구분한다.", sources: ["early"] },
  { id: "developers-indictment", date: "2021-11-22", dateLabel: "2021.11.22", period: "investigation", category: "수사·기소", track: "개발사업·민간업자", title: "김만배·남욱·정영학 기소", body: "김만배와 남욱은 배임·뇌물공여 혐의로 구속기소됐고, 정영학은 배임 혐의로 불구속기소됐다.", limit: "공소사실은 검찰의 주장이다. 개별 혐의의 유·무죄는 선고 항목에서 따로 본다.", sources: ["early"] },
  { id: "min-indictment", date: "2021-12-21", dateLabel: "2021.12.21", period: "investigation", category: "수사·기소", track: "개발사업·민간업자", title: "정민용 불구속기소", body: "공사에서 사업 실무를 맡았던 정민용이 불구속기소됐다.", limit: "민간업자 등 5인 재판과 이재명·정진상 재판은 피고인과 절차가 다르다.", sources: ["early"] },
  { id: "kim-indictment", date: "2022-11-08", dateLabel: "2022.10.19 체포 · 11.08 기소", period: "expansion", category: "수사·기소", track: "김용 정치자금", title: "김용의 불법 정치자금 의혹으로 수사 확대", body: "김용 전 민주연구원 부원장이 체포된 뒤 선거자금 수수 혐의로 구속기소됐다.", limit: "개발사업 배임 재판과 별도의 정치자금 사건이다.", sources: ["kimFirst"] },
  { id: "renewed-investigation", date: "2022-07-30", dateLabel: "2022.07.30 (보도일)", period: "expansion", category: "수사·기소", track: "이재명·정진상", title: "사업 초기 관계자를 대상으로 보강수사", body: "검찰은 2010년대 초 개발 방식 변경 당시의 추진위원회와 성남시 관계자들을 조사한 것으로 보도됐다. 기존 사업자 선정 수사보다 앞선 시기를 살피는 수사였다.", limit: "이재명의 혐의를 입증하려는 것이냐는 당시 보도의 분석은 수사 결론이 아니다.", sources: ["renewedInvestigation"] },
  { id: "jung-indictment", date: "2022-12-09", dateLabel: "2022.12.09", period: "expansion", category: "수사·기소", track: "이재명·정진상", title: "정진상 뇌물 혐의 구속기소", body: "검찰이 정진상 전 민주당 대표실 정무조정실장을 뇌물 혐의 등으로 구속기소했다.", limit: "기소와 공모 주장은 확정된 유죄 판단이 아니다.", sources: ["indictmentChronology"] },
  { id: "lee-questioning", date: "2023-01-28", dateLabel: "2023.01.28 · 02.10", period: "expansion", category: "수사·기소", track: "이재명·정진상", title: "이재명, 대장동·위례 관련 두 차례 검찰 조사", body: "검찰은 이재명을 소환해 개발사업 관련 혐의를 조사했다.", limit: "이 항목은 소환 날짜를 기록한다. 조사 진술 전문은 확보하지 못했다.", sources: ["indictmentChronology"] },
  { id: "lee-warrant", date: "2023-02-16", dateLabel: "2023.02.16", period: "expansion", category: "수사·기소", track: "이재명·정진상", title: "대장동 배임·성남FC 관련 구속영장 청구", body: "검찰은 이재명에 대한 구속영장을 청구했다.", limit: "성남FC 혐의도 함께 포함된 영장이다. 이후 다른 사건의 영장 판단과 혼동하지 않는다.", sources: ["indictmentChronology"] },
  { id: "arrest-vote", date: "2023-02-27", dateLabel: "2023.02.27", period: "expansion", category: "정치적 대응", track: "이재명·정진상", title: "국회 체포동의안 부결", body: "국회 표결에서 이재명 체포동의안이 부결됐다.", limit: "국회의 체포동의 절차이며 법원의 무죄 판단이 아니다.", sources: ["indictmentChronology"] },
  { id: "lee-indictment", date: "2023-03-22", dateLabel: "2023.03.22", period: "expansion", category: "수사·기소", track: "이재명·정진상", title: "이재명, 대장동·위례 등 혐의 불구속기소", body: "검찰은 대장동 개발 배임 등 혐의로 이재명을 재판에 넘겼다.", limit: "민간업자 재판의 결과를 이재명에 대한 선고로 대신할 수 없다.", sources: ["indictmentChronology"] },
  { id: "lee-first-trial", date: "2023-10-06", dateLabel: "2023.10.06", period: "expansion", category: "재판·절차", track: "이재명·정진상", title: "이재명·정진상 재판 첫 정식 공판", body: "이재명이 대장동·위례·성남FC 관련 첫 공판에 출석했다. 이재명 측은 혐의를 부인했다.", limit: "이재명의 선거법 사건 등 다른 재판의 결과와 구분한다.", sources: ["firstTrial"] },
  { id: "trial-arguments", date: "2023-11-04", dateLabel: "2023.11.04 (보도일)", period: "expansion", category: "의혹·반박", track: "이재명·정진상", title: "공사 손해라는 공소사실과 공익 사업이라는 반박", body: "SBS의 재판 취재 보도는 검찰의 4,895억 원 손해 주장과 이재명 측의 공공 이익을 낸 사업이라는 반박을 정리했다.", limit: "검찰이 주장한 손해액이다. 법원이 확정한 손해액이나 이재명에 대한 유죄 결과로 표시하지 않는다.", sources: ["trialArguments"] },
  { id: "kim-first-verdict", date: "2023-11-30", dateLabel: "2023.11.30", period: "expansion", category: "재판·절차", track: "김용 정치자금", title: "김용 정치자금·뇌물 사건 1심 징역 5년", body: "김용은 불법 정치자금과 뇌물 사건의 1심에서 징역 5년을 선고받았다.", limit: "김용 본인에 대한 1심 결과다. 이재명이 자금을 받았다는 확정판결로 바꿔 읽지 않는다.", sources: ["kimFirst", "kimAppeal"] },
  { id: "kim-appeal-verdict", date: "2025-02-06", dateLabel: "2025.02.06", period: "judgments", category: "재판·절차", track: "김용 정치자금", title: "김용 항소심도 징역 5년", body: "항소심이 김용에게 징역 5년을 선고하고 법정구속했다.", limit: "항소심 선고와 대법원 확정판결은 다르다. 이후 보석 절차도 따로 기록한다.", sources: ["kimAppeal"] },
  { id: "trial-attendance", date: "2024-03-19", dateLabel: "2024.03.19", period: "judgments", category: "재판·절차", track: "이재명·정진상", title: "총선 일정과 재판 출석을 둘러싼 공방", body: "이재명 측은 선거운동을 이유로 불출석 사유서를 냈지만 재판부는 받아들이지 않았다. 유동규도 이재명 없이는 증언하지 않겠다고 해 당일 증인신문이 진행되지 못했다.", limit: "출석·기일 운영에 관한 절차다. 사건의 유·무죄 결론과 구분한다.", sources: ["trial2024"] },
  { id: "lee-trial-delay", date: "2025-06-10", dateLabel: "2025.06.10", period: "judgments", category: "재판·절차", track: "이재명·정진상", title: "대통령 취임 뒤 이재명 재판 기일 추후 지정", body: "재판부가 헌법 84조를 이유로 이재명의 재판 기일을 추후 지정했다. 정진상의 재판은 계속 진행하는 것으로 보도됐다.", limit: "기일 연기는 무죄 선고나 공소 취소가 아니다. 정진상의 절차까지 모두 멈춘 것으로 표시하지 않는다.", sources: ["leeDelay"] },
  { id: "kim-bail", date: "2025-08-19", dateLabel: "2025.08.19 허가 · 20일 석방", period: "judgments", category: "재판·절차", track: "김용 정치자금", title: "김용, 보석 허가 후 불구속 상고심", body: "대법원이 김용의 보석을 허가했다. 석방 뒤 김용은 억울함을 주장하며 진실이 밝혀질 것이라는 입장을 밝혔다.", limit: "보석은 구금 상태에 관한 결정이다. 2심 유죄가 취소됐거나 무죄가 확정됐다는 의미가 아니다.", sources: ["kimBail", "kimResponse"] },
  { id: "main-verdict", date: "2025-10-31", dateLabel: "2025.10.31", period: "judgments", category: "재판·절차", track: "개발사업·민간업자", title: "민간업자 등 5인 1심: 업무상 배임 유죄", body: "김만배·유동규는 각각 징역 8년, 정민용은 6년, 정영학은 5년, 남욱은 4년을 선고받고 법정구속됐다. 업무상 배임은 유죄, 특정경제범죄가중처벌법상 배임은 무죄로 판단됐다.", limit: "일부 혐의 유죄와 일부 무죄가 함께 있는 1심이다. 이재명·정진상에 대한 선고가 아니다. 판결문 전문은 미확보다.", sources: ["mainVerdict"] },
  { id: "prosecution-no-appeal", date: "2025-11-07", dateLabel: "2025.11.07 항소 기한", period: "judgments", category: "재판·절차", track: "개발사업·민간업자", title: "검찰, 민간업자 1심 판결에 항소하지 않음", body: "검찰이 항소 기한 안에 항소장을 내지 않았다. 피고인들은 항소해 항소심 절차가 이어졌다.", limit: "검찰의 항소 포기는 사건 전체의 무죄 확정이나 피고인 항소심의 종료가 아니다.", sources: ["appealDecision", "latestTestimony"] },
  { id: "minister-response", date: "2025-11-10", dateLabel: "2025.11.10", period: "judgments", category: "정치적 대응", track: "수사·정치 논쟁", title: "정성호, 항소 포기 논란에 입장 표명", body: "정성호 법무부 장관은 항소 포기에 문제가 없다고 설명하고, 검찰에 신중하게 판단하라는 말을 했다고 밝혔다.", limit: "장관의 설명이다. 항소 결정 과정에 부당한 개입이 있었는지에 대한 사법 판단으로 표시하지 않는다.", sources: ["minister"] },
  { id: "main-appeal-start", date: "2026-01-23", dateLabel: "2026.01.23 공판준비기일", period: "recent", category: "재판·절차", track: "개발사업·민간업자", title: "민간업자 등 5인 항소심 시작", body: "서울고법에서 첫 공판준비기일이 열렸다. 피고인 측은 배임죄 성립을 다투며 공소사실을 반박했다.", limit: "공판준비기일과 정식 증인신문·선고는 구분한다. 피고인의 무죄 주장은 판결이 아니다.", sources: ["mainAppeal"] },
  { id: "gwak-separate-appeal", date: "2026-02-12", dateLabel: "2026.02.06 1심 · 02.12 검찰 항소", period: "recent", category: "재판·절차", track: "50억 클럽", title: "곽상도 부자 범죄수익 은닉 사건에 검찰 항소", body: "검찰은 곽상도 부자의 범죄수익 은닉 관련 1심 판결에 항소했다. 곽상도에 대해서는 공소기각이 선고된 것으로 보도됐다.", limit: "기존 뇌물 사건과 별도 기소된 사건이다. 공소기각을 뇌물 혐의에 대한 새로운 무죄 선고라고 표시하지 않는다.", sources: ["gwakSeparate"] },
  { id: "gwak-bribery-appeal", date: "2026-04-14", dateLabel: "2026.04.14", period: "recent", category: "재판·절차", track: "50억 클럽", title: "곽상도 뇌물 사건 항소심 재개", body: "2023년 1심에서 뇌물 혐의 무죄를 받은 곽상도의 항소심이 재개됐다. 곽상도 측은 검찰의 남욱 진술 회유 의혹을 주장했다.", limit: "뇌물 사건과 범죄수익 은닉 사건을 구분한다. 회유 의혹은 변호인 측 주장이다.", sources: ["gwakAppeal"] },
  { id: "hearing", date: "2026-04-16", dateLabel: "2026.04.16 청문회 (17일 보도)", period: "recent", category: "의혹·반박", track: "수사·정치 논쟁", title: "국정조사 청문회: 남욱의 진술 압박 주장과 반박", body: "남욱은 검찰 조사에서 진술 압박이 있었다고 주장했다. 수사 검사 측은 남욱이 계속 말을 바꿨다는 취지의 녹취를 제시하며 반박했다.", limit: "청문회에서 나온 상반된 설명이다. 조사 전체 영상·조서와 녹취 원본을 독립 검증한 것은 아니다.", sources: ["hearing"] },
  { id: "ruling-party-response", date: "2026-04-17", dateLabel: "2026.04.17", period: "recent", category: "정치적 대응", track: "수사·정치 논쟁", title: "범여권 국조위원들, 기획수사 주장과 특검 요구", body: "박성준 등 범여권 국조특위 위원들은 이재명을 겨냥한 기획수사라는 입장을 내고 특검을 통한 책임 규명을 요구했다.", limit: "위원들의 정치적 주장이다. 조사 결과나 법원의 수사 조작 인정으로 표시하지 않는다.", sources: ["hearingRulingParty"] },
  { id: "opposition-response", date: "2026-04-30", dateLabel: "2026.04.30", period: "recent", category: "정치적 대응", track: "수사·정치 논쟁", title: "국민의힘 국조위원들, 특검 비판과 위증 고발 방침", body: "국민의힘 위원들은 특검 추진을 비판하고 남욱 등의 청문회 증언을 문제 삼아 위증 고발 방침을 밝혔다.", limit: "위증이라는 고발 측 주장을 기록한다. 고발 방침이나 고발 자체는 위증 유죄 판결이 아니다.", sources: ["hearingOpposition"] },
  { id: "main-release", date: "2026-04-30", dateLabel: "2026.04.30 (5월 31일 후속 보도)", period: "recent", category: "재판·절차", track: "개발사업·민간업자", title: "유동규·김만배·남욱, 구속기간 만료로 석방", body: "유동규·김만배·남욱은 구속기간 만료로 석방된 것으로 보도됐다.", limit: "구속기간에 따른 석방이다. 항소심 무죄 선고가 아니다.", sources: ["mainBail"] },
  { id: "main-bail", date: "2026-05-07", dateLabel: "2026.05.07 (31일 보도)", period: "recent", category: "재판·절차", track: "개발사업·민간업자", title: "정민용·정영학 보석 허가, 5인 모두 불구속 상태", body: "서울고법이 정민용·정영학의 보석을 허가했다. 앞서 석방된 세 사람과 함께 5명 모두 불구속 상태가 됐다.", limit: "보석 허가와 실형 선고의 취소는 다르다. 이후 구금 상태 변화는 별도로 확인해야 한다.", sources: ["mainBail"] },
  { id: "kim-records", date: "2026-07-08", dateLabel: "2026.07.08 결정 (9일 보도)", period: "recent", category: "재판·절차", track: "김용 정치자금", title: "대법원, 검찰미래위의 김용 사건 기록 열람 요청 불허", body: "대법원은 법무부 검찰미래위원회의 김용 사건 기록 열람 요청을 허용하지 않은 것으로 보도됐다. 당시 기사는 상고심 심리가 진행 중이라고 전했다.", limit: "기록 열람에 관한 결정이며 유·무죄 선고가 아니다. 이후 확정판결 원문은 이번 조사에서 확보하지 못했다.", sources: ["kimRecords"] },
  { id: "latest-testimony", date: "2026-09-18", dateLabel: "2026.09.18 항소심", period: "recent", category: "의혹·반박", track: "개발사업·민간업자", title: "정민용, 수사에 정해진 틀이 있었다고 주장…유동규 반박", body: "정민용은 2차 수사에서 이재명·정진상·김용을 겨냥한 분위기를 인식했고, 자신의 유보적인 답변이 단정적 진술로 바뀌었다고 주장했다. 유동규는 정민용의 진술 변화를 지적하며 반박했다.", limit: "상반된 법정 진술이다. 수사 조작이 확정된 것으로 표시하지 않는다. 보도상 11월 27일 피고인 신문·결심 예정은 향후 일정이며 아직 열린 절차가 아니다.", sources: ["latestTestimony"] },
];

type RelatedVoice = { name: string; role: string; dateLabel: string; stance: string; summary: string; limit: string; sources: readonly ResearchSourceId[] };
export const relatedVoices: readonly RelatedVoice[] = [
  { name: "이재명", role: "당시 성남시장 · 2021년 경기지사", dateLabel: "2021.09 · 2023.10", stance: "공익 사업 설명 · 혐의 부인", summary: "공공 이익을 환수한 사업이라고 설명했고, 자신의 재판에서 혐의를 부인했다.", limit: "당사자의 주장과 검찰의 공소사실, 법원의 판단은 구분한다.", sources: ["leeResponse", "firstTrial"] },
  { name: "정진상", role: "전 성남시 정책비서관 · 민주당 대표실 정무조정실장", dateLabel: "2022.12 · 2025.06", stance: "뇌물 혐의 재판", summary: "뇌물 혐의 등으로 기소됐다. 이재명의 기일 연기 이후에도 재판이 이어지는 것으로 보도됐다.", limit: "절차 참여를 기록한다. 검찰이 주장한 공모를 확정 사실로 표현하지 않는다.", sources: ["indictmentChronology", "leeDelay"] },
  { name: "김만배", role: "화천대유 대주주", dateLabel: "2025.10 · 2026.01", stance: "1심 징역 8년 · 항소", summary: "민간업자 사건의 1심에서 징역 8년을 선고받았고, 피고인 측은 항소심에서 배임죄 성립을 다퉜다.", limit: "확정판결이 아닌 1심 선고와 항소심 절차다.", sources: ["mainVerdict", "mainAppeal"] },
  { name: "유동규", role: "전 성남도시개발공사 기획본부장", dateLabel: "2025.10 · 2026.09", stance: "1심 징역 8년 · 진술 공방", summary: "1심에서 징역 8년을 선고받았다. 항소심에서는 정민용이 정권 변화에 따라 진술을 바꾼다는 취지로 반박했다.", limit: "유동규의 반박도 법정 당사자의 주장이다.", sources: ["mainVerdict", "latestTestimony"] },
  { name: "남욱", role: "대장동 사업 참여 변호사", dateLabel: "2026.04", stance: "진술 압박 주장", summary: "국정조사 청문회에서 검찰 조사 중 진술 압박이 있었다고 주장했다. 수사 검사 측은 진술이 바뀌었다며 반박했다.", limit: "청문회 진술을 독립적으로 입증된 사실로 대신하지 않는다.", sources: ["hearing"] },
  { name: "정영학", role: "대장동 사업 참여 회계사", dateLabel: "2021.09 · 2025.10", stance: "녹취 제출 · 1심 징역 5년", summary: "수사기관에 녹취파일을 제출했고 민간업자 사건의 1심에서 징역 5년을 선고받았다.", limit: "녹취 제출자의 설명과 녹취 내용의 증거능력은 별도 문제다.", sources: ["early", "mainVerdict"] },
  { name: "정민용", role: "전 성남도시개발공사 전략사업팀장 · 변호사", dateLabel: "2026.09.18", stance: "수사 틀·진술 변화 주장", summary: "항소심 증언에서 수사에 정해진 틀이 있었고 유보적인 답변이 단정적 진술로 바뀌었다고 주장했다.", limit: "동일 법정에서 유동규가 반박했다. 주장과 사법적 입증을 구분한다.", sources: ["latestTestimony"] },
  { name: "김용", role: "전 민주연구원 부원장", dateLabel: "2025.02 · 08", stance: "항소심 유죄 · 억울함 주장", summary: "정치자금·뇌물 사건의 2심에서 징역 5년을 선고받았다. 보석 석방 뒤 진실이 밝혀질 것이라는 입장을 밝혔다.", limit: "김용 사건을 민간업자 배임 재판과 구분한다. 보석은 무죄 확정이 아니다.", sources: ["kimAppeal", "kimResponse"] },
  { name: "곽상도", role: "전 국민의힘 의원", dateLabel: "2026.02 · 04", stance: "50억 관련 별도 재판", summary: "뇌물 사건 항소심과 별도 범죄수익 은닉 사건이 진행됐다. 뇌물 항소심에서 검찰의 진술 회유 의혹을 주장했다.", limit: "두 사건을 하나의 선고 결과로 합치지 않는다.", sources: ["gwakSeparate", "gwakAppeal"] },
  { name: "송평수", role: "당시 이재명 경선 캠프 대변인", dateLabel: "2021.09.15", stance: "공익 환수·사업 위험 강조", summary: "SBS ‘주영진의 뉴스브리핑’에서 공영개발 전환에 따른 공공 환수와 민간의 위험 부담을 설명했다.", limit: "캠프의 설명이며 사업 정산 자료의 독립 검증은 아니다.", sources: ["debate"] },
  { name: "김경율", role: "당시 경제민주주의21 공동대표 · 회계사", dateLabel: "2021.09.15", stance: "민간 배당 구조 비판", summary: "같은 SBS 방송에서 공공의 위험 부담과 민간의 큰 배당 이익을 문제 삼았다.", limit: "전문가의 평가와 법원의 배임 판단을 구분한다.", sources: ["debate"] },
  { name: "정성호", role: "당시 법무부 장관", dateLabel: "2025.11.10", stance: "항소 포기 관련 설명", summary: "항소 포기에 문제가 없다는 입장과 검찰에 신중한 판단을 주문했다는 설명을 내놨다.", limit: "장관의 공개 설명이며 의사결정 과정의 전모를 확인한 자료는 아니다.", sources: ["minister"] },
  { name: "박성준", role: "당시 민주당 국정조사특위 위원", dateLabel: "2026.04.17", stance: "기획수사 주장 · 특검 요구", summary: "범여권 국조위원들과 함께 이재명을 겨냥한 기획수사라고 주장하며 특검을 요구했다.", limit: "공동 입장을 요약했다. 위원 전체나 민주당 인사 모두의 동일한 입장으로 확대하지 않는다.", sources: ["hearingRulingParty"] },
];
